spring.datasource.url=jdbc:postgresql://localhost:5432/example-for-graduate-work
spring.datasource.username=postgres
spring.datasource.password=skypro

spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.hibernate.default_schema=public

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.liquibase.clear-checksums=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.images.root-path=./uploads/
app.images.url-prefix=/images/